### PR TITLE
Add feature to make request to another service

### PR DESCRIPTION
**Pull request by dineshba**

### CODE REVIEW

**Comment by jskswamy** [comment]
@dineshba can we make this a nested one to simulate nested network call and show it using distributed tracking tool like [jaeger](https://www.jaegertracing.io/)

we can also setup proxy when starting dobby, in that way we don't have send the target URL all the time when we post instead we will call a endpoint in dobby and dobby will invoke the upstream based on the configuration provided during the start.

```
+---+      +---+      +---+      +---+
| A |      | B |      | C |      | D |
+---+      +---+      +---+      +---+
  |          |          |          |
  | /ping    |          |          |
  |--------->|          |          |
  |          |          |          |
  |          | /ping    |          |
  |          |--------->|          |
  |          |          |          |
  |          |          | /ping    |
  |          |          |--------->|
  |          |          |          |
  |          |          |   200 Ok |
  |          |          |<---------|
  |          |          |          |
  |          |   200 Ok |          |
  |          |<---------|          |
  |          |          |          |
  |   200 Ok |          |          |
  |<---------|          |          |
  |          |          |          |
```

**Comment by dineshba** [comment]
We do can that by running multiple dobby services @jskswamy 

we call dobby1 (using curl like below) which will call dobby2 which will call dobby3 to get the version.
```sh
curl -X POST http://dobby1/call -d 
{
    "url": "http://dobby2/call",
    "method": "POST",
    "body": {
        "url": "http://dobby3/version/",
        "method": "GET"
    }
}
```

In this way we can dynamically make any dobby to call any dobby. I think we can use this do demo distributed tracing.

Thoughts ?

**Comment by dineshba** [comment]
We can also do recursion with one dobby

```
curl -X POST http://dobby/call -d 
{
    "url": "http://dobby/call",
    "method": "POST",
    "body": {
         "url": "http://dobby/call",
         "method": "POST",
         "body": {
             "url": "http://dobby/version/",
             "method": "GET"
          }
    }
}
```

**Comment by jskswamy** [comment]
@dineshba nice thought, with this we can make routing very dynamic. Is this feature already supported in this PR?

Also ensure that necessary headers are passed to support distributed tracing

**Comment by dineshba** [comment]
Feature is already supported @jskswamy . I will look into the headers for the distributed tracing

**Comment by jskswamy** [comment]
for any error on the upstream dobby is returning `400` bad request instead it should return the server error.

```json
# request.json
{
  "url": "http://localhost:4444/call",
  "method": "POST",
  "body": {
    "url": "http://localhost:4445/call",
    "method": "POST",
    "body": {
      "url": "http://localhost:4446/return/500",
      "method": "GET"
    }
  }
}
```

```
$ curl -i -X POST --data @request.json http://localhost:4444/call
```

**Comment by jskswamy** [comment]
also `/call` should handle different `Content-Type` from the upstream server

```json
{
  "url": "http://wttr.in/chennai?format=1",
  "method": "GET"
}
```

```
$ curl -i -X POST --data @request.json http://localhost:4444/call
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Fri, 10 Jul 2020 12:47:46 GMT
Content-Length: 132

{"error":"error when decoding response from http://wttr.in/chennai?format=1: invalid character 'â' looking for beginning of value"}

```

**Comment by jskswamy** [comment]
@dineshba how about supporting adding dynamic routes using CRUD? In this way we don't have to pass on the payload all the time and when we do distributed tracing we will be understand just by looking at the URL on the flow otherwise we will only see `/call` all over the place and this will represent the real use case as well.

eg., 

```
+-------+                                                                  +---------+           +---------+
| user  |                                                                  | dobby1  |           | dobby2  |
+-------+                                                                  +---------+           +---------+
    |                                                                           |                     |
    | GET /v1/version                                                           |                     |
    |-------------------------------------------------------------------------->|                     |
    |                                                                           |                     |
    |                                                                       404 |                     |
    |<--------------------------------------------------------------------------|                     |
    |                                                                           |                     |
    | POST /proxy ("path": "/v1/version", "method": "GET", "proxy": "...")      |                     |
    |-------------------------------------------------------------------------->|                     |
    |                                                                           |                     |
    | GET /v1/version                                                           |                     |
    |-------------------------------------------------------------------------->|                     |
    |                                                                           |                     |
    |                                                                           | GET /version        |
    |                                                                           |-------------------->|
    |                                                                           |                     |
    |                                                                           |      1.x.x (200 ok) |
    |                                                                           |<--------------------|
    |                                                                           |                     |
    |                                                            1.x.x (200 ok) |                     |
    |<--------------------------------------------------------------------------|                     |
    |                                                                           |                     |
    | DELETE /proxy/v1/version                                                  |                     |
    |-------------------------------------------------------------------------->|                     |
    |                                                                           |                     |
    | GET /v1/version                                                           |                     |
    |-------------------------------------------------------------------------->|                     |
    |                                                                           |                     |
    |                                                                       404 |                     |
    |<--------------------------------------------------------------------------|                     |
    |                                                                           |                     |
```

```sh
$ curl dobby1:4444/v1/version
404 page not found

$ curl -X POST http://dobby1/proxy -d 
{
    "path": "/v1/version",
    "method": "GET",
    "proxy": {
    	"url": "http://dobby2/version",
	    "method": "GET",
    }
}

$ curl -X POST http://dobby1/v1/version
{"version":"1.0.2"}

$ curl -X DELETE http://dobby1/proxy/v1/version

$ curl dobby1:4444/v1/version
404 page not found
```

Let me know your thoughts

**Comment by dineshba** [comment]
Only one concern is in-memory state. We cannot run more than one replica of dobby. If we are running more than 1 replica of dobby, we have to make multiple post requests so that all dobby are in same state.

**Comment by jskswamy** [comment]
@dineshba even now dobby has in-memory state for the following endpoints:

1. `/health/*`
2. `/ready/*`
3. `/control/*`

If we run multiple instances of dobby and served via load balancer, calling any of the above endpoint has unpredictable outcome.

may be we can add it to `README.md` about the undesired state of running multiple instance of dobby and serving them via a single load balancer.

**Comment by dineshba** [comment]
Agree @jskswamy ... We can have such endpoint as described as before.

I feel we can have this endpoint also. Thoughts ?

**Comment by jskswamy** [comment]
@dineshba lets support both may be we need to give a different name to the endpoint `/call`, if you feel the intent is conveyed then lets go ahead with `/call` itself as the name for the endpoint.

**Comment by dineshba** [comment]
Sure.. I will add another endpoint `/proxy`.

I am kinda okay with `/call`. We are asking dobby to call the endpoint in the post body. Not able to come up with better name.

**Comment by dineshba** [comment]
Added the feature @jskswamy 

Example:
```sh
$ cat request.json
{
  "path": "/chennai/weather",
  "method": "GET",
  "proxy": {
    "url": "http://wttr.in/chennai?format=1",
    "method": "GET"
  }
}
```

Register the proxy configuration:

```sh
$ curl -X POST http://localhost:4444/proxy -d @request.json
```

Invoke the registered endpoint

```sh
$ curl http://localhost:4444/chennai/weather
```

Delete the proxy endpoint

```sh
$ curl -X DELETE http://localhost:4444/proxy -d @request.json
```

**Pull request merged**
